---
title: "Compare Approaches"
author: "Melissa Wong"
date: "12/15/2021"
output: html_document
---

# Setup

```{r libraries, results='hide', message=FALSE, warning=FALSE}

library(tidyverse)
library(broom)
library(RColorBrewer)
library(here)
```

```{r options}
options("scipen" = 1, "digits" = 4)

#knitr::opts_chunk$set(echo = FALSE)
#knitr::opts_chunk$set(message = FALSE)
#knitr::opts_chunk$set(warning = FALSE)
#knitr::opts_chunk$set(out.width = "50%")
#knitr::opts_chunk$set(fig.align = "center")

set.seed(1234)
```

# Simulate Data

```{r}

# Proportion of rounded/truncated data
prop <- seq(0.1, 0.9, 0.1)

N <- c(25, 100, 500, 1000)

params <- expand.grid(prop=prop, N=N)

alpha_true = -1
beta_true = 1
sigma_true = 1

sidx <- apply(params, 1, function(p) sample(1:p[2], p[2] * p[1], replace=FALSE))

df <-lapply(1:length(sidx), function(i) {
  tmp <- data.frame(x = rnorm(params[i, "N"], 0, 5),
                    prop = params[i, "prop"],
                    n = params[i, "N"]) %>%
  mutate(y_true = alpha_true + beta_true*x + rnorm(params[i, "N"], 0, sigma_true),
         y_round = y_true,
         y_trunc = y_true,
         iflag = 0
  )
  # Simulate a "mixture" with some subset of the data truncated/rounded
  tmp$y_round[sidx[[i]]] <- round(tmp$y_round[sidx[[i]]])
  tmp$y_trunc[sidx[[i]]] <- trunc(tmp$y_trunc[sidx[[i]]])
  tmp$iflag[sidx[[i]]] <- 1
  tmp
})

# Convert list to tidy dataframe
df_tidy <- do.call(rbind.data.frame, df)
```


```{r eval=FALSE, include=FALSE}
for (i in seq_along(N)) {
  print(
    df_tidy %>%
      filter(n==N[i]) %>%
      select(-iflag) %>% 
      pivot_longer(-c("x", "prop", "n"), names_to="data") %>%
      ggplot() +
      geom_point(aes(x=x, y=value, color=data), 
               alpha=0.2) +
      facet_grid(prop ~ data) +
      labs(title=paste("Sample Size =", N[i]))
  )
}
```

# Kolmogorv-Smirnoff Test

```{r warning=FALSE}

# Test proportion of rounding
df_tidy %>% 
  group_by(prop, n) %>% 
  summarise(tidy(ks.test(y_true, y_round))) %>% 
  ungroup() %>%
  ggplot(mapping=aes(x=prop, 
                        y=p.value, 
                        color=factor(n))) +
  geom_point() +
  geom_line() +
  geom_hline(mapping=aes(yintercept=0.05),
             color="red",
             linetype="dashed") +
  scale_x_continuous(breaks=prop) +
  labs(title="K-S test y_true vs y_round",
       x="Proportion of rounded data")

# Test proportion of truncation
df_tidy %>% 
  group_by(prop, n) %>% 
  summarise(tidy(ks.test(y_true, y_trunc))) %>% 
  ungroup() %>%
  ggplot(mapping=aes(x=prop, 
                        y=p.value, 
                        color=factor(n))) +
  geom_point() +
  geom_line() +
  geom_hline(mapping=aes(yintercept=0.05),
             color="red",
             linetype="dashed") +
  scale_x_continuous(breaks=prop) +
  labs(title="K-S test y_true vs y_trunc",
       x="Proportion of truncated data")
```


# Bayesian Models

```{r}

```


